const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  id: state => state.user.id,
  userInfo: state => state.user.infos,
  currentMap: state => state.map.currentMap,
  currentModel: state => state.map.currentModel,
  toolMap: state => state.map.toolMap,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  orgType: state => state.user.orgType,
  permission_routes: state => state.permission.routes,
  addRoutes: state => state.permission.addRoutes,
  errorLogs: state => state.errorLog.logs,
  choseProject: state => state.projectChose.chose,
  currentProject: state => state.projectChose.detail,
  choseLogo: state => state.logo.detail,
  nowMenu: state => state.user.nowmenu
}
export default getters
